### ISSUE TITLE
TypeError: $.getScript is not a function

### ISSUE THREAD

**Issue by Trost123** [withjam/jqshim-head#1]
Hi.
One of my inline scripts (on a website) has a line like this:
`(function ($) {
$.getScript("/wa-data/public/shop/themes/techauto/js/products.js?v1.0.0.1479828256", function () {
                                initProducts();
                            });
})(jQuery);`
(It's not entire script, but you can get the idea)

When I load jQuery in header - my website loads without any problem, but when I try to move jQuery to footer and use "jqshim-head.min.js" - it throws this error for this line:
TypeError: $.getScript is not a function.

It looks like I use jqshim-head right, because if I comment-out $.getScript() line - everything else (that requires jQuery) works.

Is there any way to use jQuery.getScript() with your utility?

**Comment by emersonbroga** [comment]
Try this:
wrap the call inside a document ready jquery call and it will work with jqshim.

```
$(document).ready(function() {
$.getScript("/wa-data/public/shop/themes/techauto/js/products.js?v1.0.0.1479828256", function () { initProducts(); });
)};
```

Hope it helps.

**Comment by Trost123** [comment]
Thanks.
Can't test it right now, so I'll just close this issue. (it's been around 6 months since I opened the issue, I don't use jqshim anymore)
